#version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: mlflow_postgres
    restart: always
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow_password
      POSTGRES_DB: mlflow_db
    ports:
      - "25432:25432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: mlflow_minio
    restart: always
    environment:
      MINIO_ROOT_USER: mlflow
      MINIO_ROOT_PASSWORD: mlflow_password
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # MinIO Web UI
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow_server
    restart: always
    depends_on:
      - postgres
      - minio
    environment:
      MLFLOW_TRACKING_URI: http://mlflow_nginx
      MLFLOW_S3_ENDPOINT_URL: http://mlflow_minio:9000
      AWS_ACCESS_KEY_ID: mlflow
      AWS_SECRET_ACCESS_KEY: mlflow_password
    command: >
      mlflow server 
      --backend-store-uri postgresql://mlflow:mlflow_password@mlflow_postgres:25432/mlflow_db
      --artifacts-destination s3://mlflow-artifacts
      --host 0.0.0.0 --port 15000
    ports:
      - "15000:15000"
    volumes:
      - mlflow_data:/mlflow

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: mlflow_nginx
    restart: always
    depends_on:
      - mlflow
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.htpasswd:/etc/nginx/.htpasswd

volumes:
  postgres_data:
  minio_data:
  mlflow_data:

